#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include "Adafruit_GC9A01A.h"
#include <Adafruit_MPU6050.h>
#include <Adafruit_Sensor.h>
#include "emoji_data.h"   // generated by ambient_ai/gen_emoji.py

// --- Display pins ---
#define TFT_SCK  13
#define TFT_MOSI 11
#define TFT_DC   10
#define TFT_CS    9
#define TFT_RST   8

Adafruit_GC9A01A display(TFT_CS, TFT_DC, TFT_MOSI, TFT_SCK, TFT_RST);
Adafruit_MPU6050 mpu;

// --- Eye geometry ---
const int16_t W        = 240;
const int16_t H        = 240;
const int16_t EYE_R    = 55;
const int16_t PUPIL_R  = 20;
const int16_t OUTLINE  = 2;
const int16_t LEFT_CX  = W / 4;
const int16_t RIGHT_CX = 3 * W / 4;
const int16_t CY       = H / 2;
const float   SCALE    = 10.0f;
const float   ALPHA    = 0.60f;

const int32_t EYE_R2   = (int32_t)EYE_R * EYE_R;
const int32_t INNER_R2 = (int32_t)(EYE_R - OUTLINE) * (EYE_R - OUTLINE);
const int32_t PUPIL_R2 = (int32_t)PUPIL_R * PUPIL_R;
const int16_t DIAM     = EYE_R * 2 + 1;

uint16_t eyeBuf[DIAM * DIAM];

float   fx = 0.0f, fy = 0.0f;
int16_t prevPx = 0, prevPy = 0;
bool    forceRedraw = false;
float   axBias = 0.0f, ayBias = 0.0f;

// --- Button D3 ---
#define BTN_PIN 3
bool btnPrev = false;

// --- State machine ---
// IDLE    : googly eyes follow IMU tilt
// LOADING : pupils frozen at centre, random 5-15 s fake "thinking" pause
// EMOJI   : one random emoji per eye for 10 s, picked fresh each cycle
enum State { IDLE, LOADING, EMOJI };
State         state      = IDLE;
unsigned long stateStart = 0;
unsigned long loadingDur = 0;

uint8_t emojiIdxL = 0; // emoji index for left  eye (set in enterEmoji)
uint8_t emojiIdxR = 1; // emoji index for right eye (set in enterEmoji)

const unsigned long EMOJI_DUR = 10000UL; // 10 seconds

// --- Render a standard googly eye into the shared framebuffer and blit ---
void drawEyeFB(int16_t cx, int16_t cy, int16_t px, int16_t py) {
  for (int16_t row = 0; row < DIAM; row++) {
    int32_t ey   = row - EYE_R;
    int32_t ey2  = ey * ey;
    int32_t pdy  = ey - py;
    int32_t pdy2 = pdy * pdy;
    for (int16_t col = 0; col < DIAM; col++) {
      int32_t ex  = col - EYE_R;
      int32_t er2 = ex * ex + ey2;
      int32_t pdx = ex - px;
      int32_t pr2 = pdx * pdx + pdy2;

      uint16_t color;
      if      (er2 > EYE_R2)    color = 0xFFFF; // outside → white bg
      else if (er2 >= INNER_R2) color = 0x0000; // outline ring
      else if (pr2 <= PUPIL_R2) color = 0x0000; // pupil
      else                      color = 0xFFFF; // eye white

      eyeBuf[row * DIAM + col] = color;
    }
  }
  display.drawRGBBitmap(cx - EYE_R, cy - EYE_R, eyeBuf, DIAM, DIAM);
}

// --- Render one emoji (by pool index) into an eye framebuffer and blit ---
// The tile (EMOJI_BLIT_SIZE×EMOJI_BLIT_SIZE) is centred on the eye; the
// circular outline mask naturally crops the corners into a round display.
void drawEmojiEyeFB(int16_t cx, int16_t cy, uint8_t idx) {
  const int16_t          ER  = EMOJI_BLIT_SIZE / 2;
  const uint16_t * const src = emojiPool[idx];

  for (int16_t row = 0; row < DIAM; row++) {
    int32_t ey  = row - EYE_R;
    int32_t ey2 = ey * ey;
    int     by  = (row - EYE_R) + ER;   // tile row index

    for (int16_t col = 0; col < DIAM; col++) {
      int32_t ex  = col - EYE_R;
      int32_t er2 = ex * ex + ey2;

      uint16_t color;
      if (er2 > EYE_R2) {
        color = 0xFFFF; // outside eye circle → white display bg
      } else if (er2 >= INNER_R2) {
        color = 0x0000; // black outline ring
      } else {
        int bx = (col - EYE_R) + ER;  // tile col index
        if (bx >= 0 && bx < EMOJI_BLIT_SIZE && by >= 0 && by < EMOJI_BLIT_SIZE) {
          color = pgm_read_word(&src[by * EMOJI_BLIT_SIZE + bx]);
        } else {
          color = 0xFFFF; // eye white outside tile
        }
      }
      eyeBuf[row * DIAM + col] = color;
    }
  }
  display.drawRGBBitmap(cx - EYE_R, cy - EYE_R, eyeBuf, DIAM, DIAM);
}

// --- State transition helpers ---

// D3 pressed in IDLE (or during EMOJI) → freeze eyes at centre and start
// the fake-loading countdown with a random 5–15 s duration.
void enterLoading() {
  state      = LOADING;
  stateStart = millis();
  loadingDur = (unsigned long)random(5000, 15001); // inclusive 5–15 s
  fx = fy = 0.0f;
  forceRedraw = true; // draw centred pupils once on the next frame
}

// Loading timer elapsed → pick two distinct random emoji and display for 10 s.
void enterEmoji() {
  state      = EMOJI;
  stateStart = millis();
  emojiIdxL  = random(EMOJI_COUNT);
  do { emojiIdxR = random(EMOJI_COUNT); } while (emojiIdxR == emojiIdxL);
  drawEmojiEyeFB(LEFT_CX,  CY, emojiIdxL);
  drawEmojiEyeFB(RIGHT_CX, CY, emojiIdxR);
}

// Emoji timer elapsed → resume idle googly eyes.
void enterIdle() {
  state = IDLE;
  fx = fy = 0.0f;
  forceRedraw = true; // force one draw even if IMU reads 0
}

// --- Setup ---
void setup() {
  randomSeed(analogRead(A0));
  pinMode(BTN_PIN, INPUT_PULLUP);

  display.begin();
  display.setRotation(0);
  display.fillScreen(0xFFFF);

  Wire.begin();
  if (!mpu.begin()) {
    display.fillScreen(0xF800); // solid red = sensor error
    while (1) delay(10);
  }
  mpu.setAccelerometerRange(MPU6050_RANGE_8_G);
  mpu.setFilterBandwidth(MPU6050_BAND_260_HZ);

  // IMU bias calibration: average 32 samples at rest
  float sumX = 0.0f, sumY = 0.0f;
  for (int i = 0; i < 32; i++) {
    sensors_event_t a, g, t;
    mpu.getEvent(&a, &g, &t);
    sumX += a.acceleration.y;
    sumY += -a.acceleration.x;
    delay(5);
  }
  axBias = sumX / 32.0f;
  ayBias = sumY / 32.0f;

  drawEyeFB(LEFT_CX, CY, 0, 0);
  drawEyeFB(RIGHT_CX, CY, 0, 0);
}

// --- Loop ---
void loop() {
  // Edge-detect D3 press (active low via INPUT_PULLUP)
  bool btnNow     = (digitalRead(BTN_PIN) == LOW);
  bool btnPressed = btnNow && !btnPrev;
  btnPrev = btnNow;

  // ---- State transitions ------------------------------------------------
  switch (state) {
    case IDLE:
      if (btnPressed) enterLoading();
      break;

    case LOADING:
      if (millis() - stateStart >= loadingDur) enterEmoji();
      break;

    case EMOJI:
      if (btnPressed) {
        // Interrupt during emoji: restart the loading → emoji cycle
        enterLoading();
      } else if (millis() - stateStart >= EMOJI_DUR) {
        enterIdle();
      }
      break;
  }

  // ---- Per-state rendering -----------------------------------------------
  if (state == IDLE) {
    sensors_event_t a, g, temp;
    mpu.getEvent(&a, &g, &temp);

    float   ax        = a.acceleration.y  - axBias;
    float   ay        = -a.acceleration.x - ayBias;
    int16_t maxOffset = EYE_R - PUPIL_R - OUTLINE - 2;
    float   dx        = constrain( ax * SCALE, (float)-maxOffset, (float)maxOffset);
    float   dy        = constrain(-ay * SCALE, (float)-maxOffset, (float)maxOffset);
    fx += ALPHA * (dx - fx);
    fy += ALPHA * (dy - fy);
    int16_t iPx = (int16_t)fx;
    int16_t iPy = (int16_t)fy;

    if (iPx != prevPx || iPy != prevPy || forceRedraw) {
      drawEyeFB(LEFT_CX, CY, iPx, iPy);
      drawEyeFB(RIGHT_CX, CY, iPx, iPy);
      prevPx = iPx;
      prevPy = iPy;
      forceRedraw = false;
    }

  } else if (state == LOADING) {
    // Draw centred pupils exactly once when entering LOADING
    if (forceRedraw) {
      drawEyeFB(LEFT_CX, CY, 0, 0);
      drawEyeFB(RIGHT_CX, CY, 0, 0);
      forceRedraw = false;
    }
    // Eyes stay frozen until enterEmoji() fires — nothing else to draw
  }
  // EMOJI state: eyes were rendered in enterEmoji(), no per-frame redraw needed
}
