#!/usr/bin/env python3
"""
gen_emoji.py — Bake emoji into a C PROGMEM header for ROCK/ROCK.ino.

Downloads Twemoji PNG images (72×72), resizes to EMOJI_BLIT_SIZE×EMOJI_BLIT_SIZE,
converts to RGB565 uint16_t, and writes ROCK/emoji_data.h containing two
PROGMEM arrays (emoji0[], emoji1[]) plus a matching size #define.

The sketch includes this header and blits the arrays directly into the eye
framebuffer — no Bridge, no runtime rendering.

Usage:
    python3 gen_emoji.py "😊" "🎉"    # bake two specific emoji
    python3 gen_emoji.py               # use defaults: 😊 🎉

Requirements:
    pip install Pillow requests

Twemoji licence: CC-BY 4.0 (https://github.com/twitter/twemoji)
"""

import sys
import io
from pathlib import Path

import numpy as np
import requests
from PIL import Image

# ---------------------------------------------------------------------------
# Config — must stay in sync with ROCK/ROCK.ino (ER = EMOJI_BLIT_SIZE / 2)
# ---------------------------------------------------------------------------
EMOJI_BLIT_SIZE = 36          # pixel width/height of each emoji tile
DEFAULTS        = ["😊", "🎉"]

TWEMOJI_URL = (
    "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/{cp}.png"
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def codepoint_str(emoji_char: str) -> str:
    """Return the Twemoji filename stem for an emoji, e.g. '1f60a' or '1f1fa-1f1f8'."""
    # Strip variation selector U+FE0F before building the codepoint string
    points = [f"{ord(c):x}" for c in emoji_char if ord(c) != 0xFE0F]
    return "-".join(points)


def fetch_png(emoji_char: str) -> Image.Image:
    """Download the Twemoji PNG for *emoji_char* and return as an RGBA PIL image."""
    cp  = codepoint_str(emoji_char)
    url = TWEMOJI_URL.format(cp=cp)
    try:
        r = requests.get(url, timeout=10)
        r.raise_for_status()
        return Image.open(io.BytesIO(r.content)).convert("RGBA")
    except Exception as exc:
        raise RuntimeError(
            f"Could not fetch emoji '{emoji_char}' (codepoint '{cp}')\n"
            f"URL tried: {url}\nError: {exc}"
        ) from exc


def to_rgb565(img: Image.Image, size: int = EMOJI_BLIT_SIZE) -> list[int]:
    """Resize *img* to *size*×*size*, composite onto white, return RGB565 list."""
    img = img.resize((size, size), Image.LANCZOS)

    # Flatten alpha onto a white background
    bg = Image.new("RGBA", (size, size), (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    rgb = np.array(bg.convert("RGB"), dtype=np.uint16)

    r      = rgb[:, :, 0] >> 3          # 5 bits
    g      = rgb[:, :, 1] >> 2          # 6 bits
    b      = rgb[:, :, 2] >> 3          # 5 bits
    rgb565 = ((r << 11) | (g << 5) | b).flatten()
    return rgb565.tolist()


def c_array(name: str, pixels: list[int]) -> str:
    """Format *pixels* as a C uint16_t PROGMEM array named *name*."""
    n      = len(pixels)
    cols   = 12
    lines  = [f"const uint16_t {name}[{n}] PROGMEM = {{"]
    for i in range(0, n, cols):
        chunk  = pixels[i : i + cols]
        trail  = "," if i + cols < n else ""
        lines.append("  " + ", ".join(f"0x{v:04X}" for v in chunk) + trail)
    lines.append("};")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    emojis = sys.argv[1:] if len(sys.argv) > 1 else DEFAULTS

    if len(emojis) != 2:
        print("Usage: python3 gen_emoji.py '<emoji1>' '<emoji2>'", file=sys.stderr)
        print(f"  e.g. python3 gen_emoji.py '😊' '🎉'", file=sys.stderr)
        sys.exit(1)

    out = Path(__file__).parent.parent / "ROCK" / "emoji_data.h"

    header_lines = [
        "// Auto-generated by ambient_ai/gen_emoji.py — do not edit by hand.",
        f"// Emoji: {' '.join(emojis)}  |  {EMOJI_BLIT_SIZE}x{EMOJI_BLIT_SIZE} px  RGB565",
        "// Twemoji © Twitter (CC-BY 4.0)",
        "#pragma once",
        f"#define EMOJI_BLIT_SIZE {EMOJI_BLIT_SIZE}",
        "",
    ]

    for idx, char in enumerate(emojis):
        print(f"Fetching {char} (codepoint: {codepoint_str(char)}) ...", end=" ", flush=True)
        img    = fetch_png(char)
        pixels = to_rgb565(img)
        header_lines.append(c_array(f"emoji{idx}", pixels))
        header_lines.append("")
        print("done")

    out.write_text("\n".join(header_lines))
    print(f"\nWritten → {out}")
    print(f"Now recompile ROCK/ROCK.ino to pick up the new emoji.")


if __name__ == "__main__":
    main()
