#!/usr/bin/env python3
"""
gen_emoji.py — Bake emoji into a C PROGMEM header for ROCK/ROCK.ino.

Downloads Twemoji PNG images (72×72), resizes to EMOJI_BLIT_SIZE×EMOJI_BLIT_SIZE,
converts to RGB565 uint16_t, and writes ROCK/emoji_data.h with:
  - One PROGMEM array per emoji  (emoji0[], emoji1[], …)
  - EMOJI_COUNT  define
  - emojiPool[]  pointer array for runtime random selection

The sketch picks two random distinct indices from emojiPool on every button press
and blits one emoji per eye — no Bridge, no runtime rendering needed.

Usage:
    python3 gen_emoji.py                          # 8 built-in defaults
    python3 gen_emoji.py "😊" "😂" "🎉" "🌟"    # custom set (≥ 2 emoji)

Requirements:
    pip install Pillow requests

Twemoji licence: CC-BY 4.0 (https://github.com/twitter/twemoji)
"""

import sys
import io
from pathlib import Path

import numpy as np
import requests
from PIL import Image

# ---------------------------------------------------------------------------
# Config — EMOJI_BLIT_SIZE must stay in sync with ROCK/ROCK.ino
# 90 px fills the inner eye circle (radius 53) nicely; corners are clipped
# by the circular mask, giving a natural round crop.
# ---------------------------------------------------------------------------
EMOJI_BLIT_SIZE = 90

DEFAULTS = ["😊", "😂", "🎉", "🌟", "🔥", "😎", "😍", "🤖"]

TWEMOJI_URL = (
    "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/{cp}.png"
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def codepoint_str(emoji_char: str) -> str:
    """Return the Twemoji filename stem, e.g. '1f60a' or '1f1fa-1f1f8'."""
    points = [f"{ord(c):x}" for c in emoji_char if ord(c) != 0xFE0F]
    return "-".join(points)


def fetch_png(emoji_char: str) -> Image.Image:
    """Download the Twemoji PNG for *emoji_char* and return as an RGBA PIL image."""
    cp  = codepoint_str(emoji_char)
    url = TWEMOJI_URL.format(cp=cp)
    try:
        r = requests.get(url, timeout=10)
        r.raise_for_status()
        return Image.open(io.BytesIO(r.content)).convert("RGBA")
    except Exception as exc:
        raise RuntimeError(
            f"Could not fetch emoji '{emoji_char}' (codepoint '{cp}')\n"
            f"URL tried: {url}\nError: {exc}"
        ) from exc


def to_rgb565(img: Image.Image, size: int = EMOJI_BLIT_SIZE) -> list[int]:
    """Resize *img* to *size*×*size*, composite onto white, return RGB565 list."""
    img = img.resize((size, size), Image.LANCZOS)
    bg  = Image.new("RGBA", (size, size), (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    rgb    = np.array(bg.convert("RGB"), dtype=np.uint16)
    r      = rgb[:, :, 0] >> 3
    g      = rgb[:, :, 1] >> 2
    b      = rgb[:, :, 2] >> 3
    return ((r << 11) | (g << 5) | b).flatten().tolist()


def c_array(name: str, pixels: list[int]) -> str:
    """Format *pixels* as a named uint16_t PROGMEM C array."""
    n, cols = len(pixels), 12
    lines   = [f"const uint16_t {name}[{n}] PROGMEM = {{"]
    for i in range(0, n, cols):
        chunk = pixels[i : i + cols]
        trail = "," if i + cols < n else ""
        lines.append("  " + ", ".join(f"0x{v:04X}" for v in chunk) + trail)
    lines.append("};")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    emojis = sys.argv[1:] if len(sys.argv) > 1 else DEFAULTS

    if len(emojis) < 2:
        print("Provide at least 2 emoji, e.g.:", file=sys.stderr)
        print("  python3 gen_emoji.py '😊' '😂' '🎉'", file=sys.stderr)
        sys.exit(1)

    out = Path(__file__).parent.parent / "ROCK" / "emoji_data.h"

    lines = [
        "// Auto-generated by ambient_ai/gen_emoji.py — do not edit by hand.",
        f"// Emoji: {' '.join(emojis)}  |  {EMOJI_BLIT_SIZE}x{EMOJI_BLIT_SIZE} px  RGB565",
        "// Twemoji © Twitter (CC-BY 4.0)",
        "#pragma once",
        f"#define EMOJI_BLIT_SIZE {EMOJI_BLIT_SIZE}",
        f"#define EMOJI_COUNT     {len(emojis)}",
        "",
    ]

    for idx, char in enumerate(emojis):
        print(f"Fetching {char} ({codepoint_str(char)}) ...", end=" ", flush=True)
        img    = fetch_png(char)
        pixels = to_rgb565(img)
        lines.append(c_array(f"emoji{idx}", pixels))
        lines.append("")
        print("done")

    # Pointer pool — lets the sketch index at runtime without a switch/case
    pool_entries = ", ".join(f"emoji{i}" for i in range(len(emojis)))
    lines += [
        f"const uint16_t * const emojiPool[EMOJI_COUNT] = {{ {pool_entries} }};",
        "",
    ]

    out.write_text("\n".join(lines))
    print(f"\nWritten → {out}  ({len(emojis)} emoji, {EMOJI_BLIT_SIZE}px tiles)")
    print("Recompile ROCK/ROCK.ino to pick up the new pool.")


if __name__ == "__main__":
    main()
